export const SET_COURSES = 'COURSES/SET_COURSES';
export const ADD_COURSE = 'COURSES/ADD_COURSE';
export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
export const UPDATE_COURSE = 'COURSES/UPDATE_COURSE';
